### ISSUE TITLE
代码里的测试用例生成的pfx用户证书安装不到Mac上？

### ISSUE THREAD

**Issue by 806computervision** [viakiba/viakiba#21]
![WechatIMG1622](https://user-images.githubusercontent.com/18653957/103859463-0b327d80-50f5-11eb-8bb3-6a12f3e1531a.jpeg)

**Comment by 806computervision** [comment]
是不是这个genfpx 函数有问题呀？

**Comment by viakiba** [comment]
自签证书 mac认为不可信 所以是无效的 需要信任他
